### ISSUE TITLE
When switching startpos, whenever I press right or left, it always switch to the previous startpos, and not the next (If I press the right button)

### ISSUE THREAD

**Issue by Geming400** [TheSillyDoggo/Startpos-Switcher#1]
When I go in a level with starposes, I want to go to the next startpos but it go to the previous one
Here is a video:

https://github.com/TheSillyDoggo/Startpos-Switcher/assets/101340400/5f85b684-1c21-4cdd-8da6-6e579326a9e0

**Comment by TheSillyDoggo** [comment]
I know, I fixed all the crashes and stuff I'm just too lazy to upload it to geode indexer

**Comment by Geming400** [comment]
ok:)
You are just lazy to build the mod, why not
